Repository Lonor/Tranclite, pull requests merged in 2020-11, with the labels that each got.

#2 fix some words traslation error (#1)
  cli.js
Labels: bug

#4 meow
  cli.js
Labels: approved, lgtm

#5 npm package
  README.md
Labels: approved, lgtm, size/XS, ¯\_(ツ)_/¯
